name: Docker Image CI

on:
  push:
    branches: 
      - master
jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH and deploy node app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ~/nodejs_githubaction
          git pull origin master
          docker-compose up --build -d
          
